package com.maxcom.facturas.cfdi;

import java.util.ArrayList;

import java.util.List;

import org.tempuri.Cancelar;
import org.tempuri.OutputOfCancelar;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.2.0.6183

public class CancelacionServiceSoapClient {
    public static void main(String[] args) {
        CancelacionService cancelacionService = new CancelacionService();
        CancelacionServiceSoap cancelacionServiceSoap = cancelacionService.getCancelacionServiceSoap();
        // Add your code to call the desired methods.

        String rfc = "MTE960228KT0";
        String serie = "MB";

        OutputOfCancelar respuesta = null;

        System.out.println("Inicio:" + new java.util.Date());

        List<Integer> lFolios = new ArrayList<Integer>();
        lFolios.add(200326257);
        lFolios.add(200326258);
        lFolios.add(200326262);
        lFolios.add(200326264);
        lFolios.add(200326265);
        lFolios.add(200326266);
        lFolios.add(200326267);
        lFolios.add(200326268);
        lFolios.add(200326269);
        lFolios.add(200326270);
        lFolios.add(200326273);
        lFolios.add(200326274);
        lFolios.add(200326276);
        lFolios.add(200326278);
        
        
        for (Integer folioFactura : lFolios) {

            respuesta = cancelacionServiceSoap.cancelarCFDI(rfc, serie, folioFactura);
            
            System.out.println("Id:" + respuesta.getId());
            System.out.println("Resultado:" + respuesta.getResultado());
            Cancelar cancelar = respuesta.getObjeto();
            System.out.println("cancelar:" + cancelar);
            System.out.println(">>>>>>>>>>>>>>>>>>>>>");
                        
            
        }

        System.out.println("Fin:" + new java.util.Date());

    }
}
