
package com.maxcom.facturas.cfdi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.tempuri.ObjectFactory;
import org.tempuri.OutputOfCancelar;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CancelacionServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CancelacionServiceSoap {


    /**
     * 
     * @param serie
     * @param folio
     * @param rfc
     * @return
     *     returns org.tempuri.OutputOfCancelar
     */
    @WebMethod(operationName = "CancelarCFDI", action = "http://tempuri.org/CancelarCFDI")
    @WebResult(name = "CancelarCFDIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelarCFDI", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarCFDI")
    @ResponseWrapper(localName = "CancelarCFDIResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarCFDIResponse")
    public OutputOfCancelar cancelarCFDI(
        @WebParam(name = "rfc", targetNamespace = "http://tempuri.org/")
        String rfc,
        @WebParam(name = "serie", targetNamespace = "http://tempuri.org/")
        String serie,
        @WebParam(name = "folio", targetNamespace = "http://tempuri.org/")
        int folio);

    /**
     * 
     * @param uuid
     * @param rfc
     * @return
     *     returns org.tempuri.OutputOfCancelar
     */
    @WebMethod(operationName = "CancelarCFDI_UUID", action = "http://tempuri.org/CancelarCFDI_UUID")
    @WebResult(name = "CancelarCFDI_UUIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelarCFDI_UUID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarCFDIUUID")
    @ResponseWrapper(localName = "CancelarCFDI_UUIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarCFDIUUIDResponse")
    public OutputOfCancelar cancelarCFDIUUID(
        @WebParam(name = "rfc", targetNamespace = "http://tempuri.org/")
        String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://tempuri.org/")
        String uuid);

}
