
package com.maxcom.facturas.cfdi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CancelacionService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.16.3.195/WebService/CancelacionService.asmx?wsdl#%7Bhttp%3A%2F%2Ftempuri.org%2F%7DCancelacionService")
public class CancelacionService
    extends Service
{

    private final static URL CANCELACIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.maxcom.facturas.cfdi.CancelacionService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.maxcom.facturas.cfdi.CancelacionService.class.getResource(".");
            url = new URL(baseUrl, "http://172.16.3.195/WebService/CancelacionService.asmx?wsdl#%7Bhttp%3A%2F%2Ftempuri.org%2F%7DCancelacionService");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.3.195/WebService/CancelacionService.asmx?wsdl#%7Bhttp%3A%2F%2Ftempuri.org%2F%7DCancelacionService', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CANCELACIONSERVICE_WSDL_LOCATION = url;
    }

    public CancelacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CancelacionService() {
        super(CANCELACIONSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "CancelacionService"));
    }

    /**
     * 
     * @return
     *     returns CancelacionServiceSoap
     */
    @WebEndpoint(name = "CancelacionServiceSoap")
    public CancelacionServiceSoap getCancelacionServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "CancelacionServiceSoap"), CancelacionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelacionServiceSoap
     */
    @WebEndpoint(name = "CancelacionServiceSoap")
    public CancelacionServiceSoap getCancelacionServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CancelacionServiceSoap"), CancelacionServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CancelacionServiceSoap
     */
    @WebEndpoint(name = "CancelacionServiceSoap12")
    public CancelacionServiceSoap getCancelacionServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "CancelacionServiceSoap12"), CancelacionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelacionServiceSoap
     */
    @WebEndpoint(name = "CancelacionServiceSoap12")
    public CancelacionServiceSoap getCancelacionServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CancelacionServiceSoap12"), CancelacionServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CancelacionServiceHttpGet
     */
    @WebEndpoint(name = "CancelacionServiceHttpGet")
    public CancelacionServiceHttpGet getCancelacionServiceHttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "CancelacionServiceHttpGet"), CancelacionServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelacionServiceHttpGet
     */
    @WebEndpoint(name = "CancelacionServiceHttpGet")
    public CancelacionServiceHttpGet getCancelacionServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CancelacionServiceHttpGet"), CancelacionServiceHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns CancelacionServiceHttpPost
     */
    @WebEndpoint(name = "CancelacionServiceHttpPost")
    public CancelacionServiceHttpPost getCancelacionServiceHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "CancelacionServiceHttpPost"), CancelacionServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelacionServiceHttpPost
     */
    @WebEndpoint(name = "CancelacionServiceHttpPost")
    public CancelacionServiceHttpPost getCancelacionServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CancelacionServiceHttpPost"), CancelacionServiceHttpPost.class, features);
    }

}
