
package com.maxcom.facturas.cfdi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.tempuri.ObjectFactory;
import org.tempuri.OutputOfCancelar;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CancelacionServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CancelacionServiceHttpPost {


    /**
     * 
     * @param serie
     * @param folio
     * @param rfc
     * @return
     *     returns org.tempuri.OutputOfCancelar
     */
    @WebMethod(operationName = "CancelarCFDI")
    @WebResult(name = "OutputOfCancelar", targetNamespace = "http://tempuri.org/", partName = "Body")
    public OutputOfCancelar cancelarCFDI(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rfc")
        String rfc,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "serie")
        String serie,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "folio")
        String folio);

    /**
     * 
     * @param uuid
     * @param rfc
     * @return
     *     returns org.tempuri.OutputOfCancelar
     */
    @WebMethod(operationName = "CancelarCFDI_UUID")
    @WebResult(name = "OutputOfCancelar", targetNamespace = "http://tempuri.org/", partName = "Body")
    public OutputOfCancelar cancelarCFDIUUID(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rfc")
        String rfc,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "uuid")
        String uuid);

}
