package com.maxcom.facturas.cfdi;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.2.0.6183

public class CancelacionServiceHttpGetClient
{
  public static void main(String [] args)
  {
    CancelacionService cancelacionService = new CancelacionService();
    CancelacionServiceHttpGet cancelacionServiceHttpGet = cancelacionService.getCancelacionServiceHttpGet();
    // Add your code to call the desired methods.
  }
}
